corpus_name: wiki18
retrieve_model: facebook/contriever-msmarco
corpus: /root/sqc/Rag_Agent_Search/retrieval/corpus/psgs_w100.tsv
corpus_embeddings: /root/sqc/rag_agent_search/retrieval/corpus/wikipedia_embeddings
n_subquantizers: 32
n_bits: 8
nlist: 30000
save_or_load_index: True
indexing_batch_size: 5000000  # 所有数据都读进去来
validation_workers: 32
per_gpu_batch_size: 512
question_maxlength: 256
projection_size: 768  # embedding 维度
lowercase: True
normalize_text: True
no_fp16: False
use_gpu: True
index_type: FlatIP
index_batch_size: 4096